apiVersion: v1
kind: Service
metadata:
  name: pm-mlflow-service
  namespace: poormans-mlops
spec:
  type: NodePort
  selector:
    app: pm-mlflow
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30009
