---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: poormans-mlops
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: pm-mlops-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-mlflow-deployment
  namespace: poormans-mlops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pm-mlflow
  template:
    metadata:
      labels:
        app: pm-mlflow
    spec:
      containers:
      - name: pm-mlflow
        image: asdyns/pm-mlflow:latest
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mlflow-pvc
