apiVersion: v1
kind: Pod
metadata:
  name: pm-mlflow
  namespace: poormans-mlops
  labels:
    name: pm-mlflow
spec:
  containers:
  - name: pm-mlflow
    image: asdyns/pm-mlflow:latest
    ports:
      - containerPort: 5000
